### PR TITLE
Update to foundry v10

### PR DESCRIPTION
**Pull request by anthonyhuber57**
Fixing importing 104337

### CODE REVIEW

**Comment by anthonyhuber57** [comment]
@zarmstrong This fixes your 104337 import

**Comment by anthonyhuber57** [comment]
@zarmstrong I noticed you are using logs to debug. It is a lot easier if you use f12 and set breakpoints. This only really works if you change your module.json to use the non-minified file though. Gives you a lot of insight into how the data is structured. Also lets you step into the foundry and pf2e code to understand how they are handling the data

**Comment by zarmstrong** [comment]
I do both :)

**Comment by anthonyhuber57** [comment]
@zarmstrong Turns out the reason some of my spellcasting entries seemed to not be working is because my innate entries are exported from Pathbuilder as prepared, and PF2e updated to not show unprepared spells. Seems this issue is only able to be fixed from the app

**Comment by anthonyhuber57** [comment]
@zarmstrong Is there an update on this?

**Comment by zarmstrong** [comment]
Thanks, I'll try to look this weekend, life has been very, very busy!

**Comment by Cediddi** [comment]
Hey, everyone. After the OGL crisis hit, I've been thinking about moving from roll20 and 5e to foundry and pf2e. I've found this merge request by total coincidence. Too bad I'm neither a great JS developer, nor used either foundry or pathbuilder  yet :joy:

Meanwhile, I wish you both good luck on this PR. :v:

**Comment by idrillacerda** [comment]
I downloaded this file (https://github.com/anthonyhuber57/foundry-pathbuilder2e-import/tree/Update-to-foundry-v10 and put it in the pathbuilder folder replacing the files. however, even after activating the pathbuilder, the n icon appears on top of the sheet. Would you know how to resolve?

**Comment by anthonyhuber57** [comment]
You need to change the configuration file to point at the non-minified file
as opposed to the minified one

**Comment by idrillacerda** [comment]
@anthonyhuber57 Could you explain to me how to do this? I didn't understand well

**Comment by zarmstrong** [comment]
merged and pushed. @idrillacerda please try downloading the module through foundry. you might need to download via the json/manual way.

**Comment by zarmstrong** [comment]
https://github.com/zarmstrong/foundry-pathbuilder2e-import/raw/master/module.json

**Pull request merged**
